/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;

/**
 *
 * @author Rayson
 */
public class Login extends javax.swing.JFrame {
    LoginController controller;
    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        controller=new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        btnMaximize = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bannerTotal = new javax.swing.JPanel();
        bannerSistem1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        espeBG = new javax.swing.JPanel();
        pnOverlay = new javax.swing.JPanel();
        lbBG = new javax.swing.JLabel();
        bannerMiespe = new javax.swing.JPanel();
        labelEspe = new javax.swing.JLabel();
        TextUser = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        textPassword = new javax.swing.JPasswordField();
        errorPassword = new javax.swing.JLabel();
        errorUser = new javax.swing.JLabel();
        jBGOpaque7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 16));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cerrarNegro.png"))); // NOI18N

        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/maximizarNegro.png"))); // NOI18N

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minimizarNegro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1286, Short.MAX_VALUE)
                .addComponent(btnMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaximize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose)
            .addComponent(btnMaximize)
            .addComponent(btnMinimize)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1352, 20));

        jScrollPane2.setInheritsPopupMenu(true);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1330, 600));

        bannerTotal.setPreferredSize(new java.awt.Dimension(1300, 800));
        bannerTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bannerSistem1.setBackground(new java.awt.Color(255, 255, 255));
        bannerSistem1.setPreferredSize(new java.awt.Dimension(410, 65));
        bannerSistem1.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 2, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ESTUDIANTES");
        jLabel3.setPreferredSize(new java.awt.Dimension(410, 44));
        bannerSistem1.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SISTEMA INTEGRADO DE INFORMACION");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(410, 20));
        bannerSistem1.add(jLabel4, java.awt.BorderLayout.CENTER);

        bannerTotal.add(bannerSistem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 375, -1, -1));

        espeBG.setBackground(new java.awt.Color(255, 255, 255));
        espeBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnOverlay.setPreferredSize(new java.awt.Dimension(850, 800));

        lbBG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesBG/Iasa.jpg"))); // NOI18N

        javax.swing.GroupLayout pnOverlayLayout = new javax.swing.GroupLayout(pnOverlay);
        pnOverlay.setLayout(pnOverlayLayout);
        pnOverlayLayout.setHorizontalGroup(
            pnOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
            .addGroup(pnOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOverlayLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbBG, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
        );
        pnOverlayLayout.setVerticalGroup(
            pnOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
            .addGroup(pnOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOverlayLayout.createSequentialGroup()
                    .addComponent(lbBG, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        espeBG.add(pnOverlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 800));

        bannerTotal.add(espeBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bannerMiespe.setBackground(new java.awt.Color(255, 255, 255));
        bannerMiespe.setPreferredSize(new java.awt.Dimension(449, 800));
        bannerMiespe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEspe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo-MiESPE.png"))); // NOI18N
        labelEspe.setPreferredSize(new java.awt.Dimension(375, 65));
        bannerMiespe.add(labelEspe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, -1, 90));

        TextUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextUser.setForeground(new java.awt.Color(204, 204, 204));
        TextUser.setText("usuario");
        TextUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TextUser.setPreferredSize(new java.awt.Dimension(375, 35));
        bannerMiespe.add(TextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 50));

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("INGRESAR");
        btnStart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnStart.setBorderPainted(false);
        btnStart.setPreferredSize(new java.awt.Dimension(375, 50));
        bannerMiespe.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        textPassword.setText("225555");
        textPassword.setPreferredSize(new java.awt.Dimension(375, 35));
        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });
        bannerMiespe.add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 50));

        errorPassword.setForeground(new java.awt.Color(255, 0, 0));
        errorPassword.setText("Error");
        bannerMiespe.add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 375, 22));

        errorUser.setForeground(new java.awt.Color(255, 0, 0));
        errorUser.setText("Error");
        bannerMiespe.add(errorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 375, 22));

        bannerTotal.add(bannerMiespe, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 460, -1));
        bannerTotal.add(jBGOpaque7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 880, 795));

        jScrollPane2.setViewportView(bannerTotal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 1360, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField TextUser;
    private javax.swing.JPanel bannerMiespe;
    private javax.swing.JPanel bannerSistem1;
    private javax.swing.JPanel bannerTotal;
    public javax.swing.JLabel btnClose;
    public javax.swing.JLabel btnMaximize;
    public javax.swing.JLabel btnMinimize;
    public javax.swing.JButton btnStart;
    public javax.swing.JLabel errorPassword;
    public javax.swing.JLabel errorUser;
    private javax.swing.JPanel espeBG;
    public javax.swing.JLabel jBGOpaque7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelEspe;
    public javax.swing.JLabel lbBG;
    public javax.swing.JPanel pnOverlay;
    public javax.swing.JPasswordField textPassword;
    // End of variables declaration//GEN-END:variables
}
