/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface.Cliente;

/**
 *
 * @author Rayson
 */
public class PanelCliente extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PanelCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelCliente = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        derechos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ayuda = new javax.swing.JPanel();
        ClientePanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        ComprarButtom = new javax.swing.JButton();
        PublicarButtom = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        PanelCliente.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Ayuda");
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 70));

        derechos.setText("@");
        jPanel4.add(derechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 170, 90));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 450));

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/Logo.jpeg"))); // NOI18N
        jPanel5.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Version 1.0");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 730, 90));

        Ayuda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClientePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setText("Comprar Propiedades");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        ClientePanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 150, 120));

        jTextField3.setEditable(false);
        jTextField3.setText("Publicar Propiedad");
        ClientePanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 170, 120));

        ComprarButtom.setText("Entrar");
        ClientePanel.add(ComprarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 150, 50));

        PublicarButtom.setText("Entrar");
        PublicarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicarButtomActionPerformed(evt);
            }
        });
        ClientePanel.add(PublicarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 170, 50));

        jTextField1.setEditable(false);
        jTextField1.setText("MOSTRAR PROPIEDADES PUBLICADAS");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        ClientePanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 120));

        jLabel2.setText("MENU DEL CLIENTE");
        ClientePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jButton4.setText("Entrar");
        ClientePanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 50));

        Ayuda.add(ClientePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 450));

        jPanel3.add(Ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 560, 420));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -5;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        PanelCliente.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void PublicarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicarButtomActionPerformed
        IngresoPropiedades ingreso=new IngresoPropiedades();
        ingreso.setVisible(true);
    }//GEN-LAST:event_PublicarButtomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ayuda;
    private javax.swing.JPanel ClientePanel;
    private javax.swing.JButton ComprarButtom;
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JButton PublicarButtom;
    private javax.swing.JLabel derechos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
