package Login.Vista;

import Login.Controlador.ControladorLogin;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rayson
 */
public class VistaLogin extends javax.swing.JFrame {
    private ControladorLogin controller;
     public VistaLogin() {
        this.controller=new ControladorLogin(this);
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void  InitComponents(){
        initComponents();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorPassword = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        errorId = new javax.swing.JLabel();
        passwordL = new javax.swing.JLabel();
        usuarioL = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        ButtomIniciar = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        languajeCombo = new javax.swing.JComboBox<>();
        CheckMostrarContra = new javax.swing.JCheckBox();
        RegistrarseButtom = new javax.swing.JButton();
        eresNuevoLabel = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setLocation(new java.awt.Point(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorPassword.setBackground(new java.awt.Color(255, 51, 51));
        errorPassword.setFont(new java.awt.Font("Segoe UI Emoji", 2, 12)); // NOI18N
        errorPassword.setForeground(new java.awt.Color(255, 51, 51));
        errorPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorPassword.setText("Contraseña Incorrecta");
        getContentPane().add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 260, 20));

        login.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        login.setText("Ingresar");
        login.setToolTipText("");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, 40));

        errorId.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        errorId.setForeground(new java.awt.Color(255, 51, 102));
        errorId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorId.setText("ID Invalido");
        getContentPane().add(errorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 340, 20));

        passwordL.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        passwordL.setText("CONTRASEÑA");
        getContentPane().add(passwordL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 160, -1));

        usuarioL.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        usuarioL.setText("USUARIO");
        getContentPane().add(usuarioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        idText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idText.setActionCommand("<Not Set>");
        idText.setBorder(null);
        idText.setVerifyInputWhenFocusTarget(false);
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        getContentPane().add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, 40));

        passwordText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 220, 40));

        ButtomIniciar.setBackground(new java.awt.Color(0, 0, 0));
        ButtomIniciar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        ButtomIniciar.setText("Ingresar");
        ButtomIniciar.setToolTipText("");
        ButtomIniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtomIniciar.setContentAreaFilled(false);
        ButtomIniciar.setFocusPainted(false);
        ButtomIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtomIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 100, 30));

        exitButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        exitButton.setText("Salir");
        exitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.setContentAreaFilled(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        languajeCombo.setEditable(true);
        languajeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        languajeCombo.setOpaque(true);
        languajeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languajeComboActionPerformed(evt);
            }
        });
        getContentPane().add(languajeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 90, -1));

        CheckMostrarContra.setText("Mostrar Contraseña");
        CheckMostrarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckMostrarContraActionPerformed(evt);
            }
        });
        getContentPane().add(CheckMostrarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 220, -1));

        RegistrarseButtom.setText("REGISTRARSE");
        RegistrarseButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseButtomActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarseButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        eresNuevoLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        eresNuevoLabel.setForeground(new java.awt.Color(255, 255, 255));
        eresNuevoLabel.setText("Eres nuevo por aqui, Registrate");
        getContentPane().add(eresNuevoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        FONDO.setDoubleBuffered(true);
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed

    }//GEN-LAST:event_idTextActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed

    }//GEN-LAST:event_passwordTextActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed

    }//GEN-LAST:event_exitButtonActionPerformed

    private void CheckMostrarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckMostrarContraActionPerformed

    }//GEN-LAST:event_CheckMostrarContraActionPerformed

    private void ButtomIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomIniciarActionPerformed
  
    }//GEN-LAST:event_ButtomIniciarActionPerformed
   
    private void languajeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languajeComboActionPerformed

    }//GEN-LAST:event_languajeComboActionPerformed

    private void RegistrarseButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseButtomActionPerformed

    }//GEN-LAST:event_RegistrarseButtomActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* Ifor details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtomIniciar;
    public javax.swing.JCheckBox CheckMostrarContra;
    public javax.swing.JLabel FONDO;
    public javax.swing.JButton RegistrarseButtom;
    public javax.swing.JLabel eresNuevoLabel;
    public javax.swing.JLabel errorId;
    public javax.swing.JLabel errorPassword;
    public javax.swing.JButton exitButton;
    public javax.swing.JTextField idText;
    public javax.swing.JComboBox<String> languajeCombo;
    public javax.swing.JLabel login;
    public javax.swing.JLabel passwordL;
    public javax.swing.JPasswordField passwordText;
    public javax.swing.JLabel usuarioL;
    // End of variables declaration//GEN-END:variables
}
