/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login.Vista;


import ConexionBD.ConexionBDClientes;
import Login.Controlador.ControladorClienteNuevo;
import elmain.ImageRenderer;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rayson
 */
public class VistaClienteNuevo extends javax.swing.JFrame {
    private ControladorClienteNuevo control;
        private DefaultTableModel tableModel;
    /**
     * Creates new form MenuPrincipal
     */
    public VistaClienteNuevo() {
        this.control=new ControladorClienteNuevo(this);
        tableModel=new DefaultTableModel(new Object [][]{}, new String[]{"Imagen","CI","Nombres Completos","Telefono","Email","Genero","Fecha"})
        {
            @Override
            public boolean isCellEditable(int row,int column){
                return false ;
            }
            @Override
            public Class<?> getColumnClass(int column){
                if(column ==0){
                    return ImageIcon.class;
                }
                return Object.class;
            }
        };
        ConexionBDClientes conexionBD=new ConexionBDClientes();
        conexionBD.actualizarTablaMongo(tableModel);
        tablaMongo.setModel(tableModel);
        tablaMongo.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablaMongo.setRowHeight(50);
        tablaMongo.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer());
        
    }
    public void InitComponents(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NombresLabel = new javax.swing.JLabel();
        anioLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        errorNames = new javax.swing.JLabel();
        telfLabel = new javax.swing.JLabel();
        errorContra = new javax.swing.JLabel();
        errorPhone = new javax.swing.JLabel();
        errorCedula = new javax.swing.JLabel();
        namesText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        saveTable = new javax.swing.JButton();
        mesCombo = new javax.swing.JComboBox<>();
        genderLabel = new javax.swing.JLabel();
        languajeCombo = new javax.swing.JComboBox<>();
        cedulaText = new javax.swing.JTextField();
        cedulaLabel = new javax.swing.JLabel();
        contraLabel = new javax.swing.JLabel();
        errorEmail = new javax.swing.JLabel();
        generoCombo = new javax.swing.JComboBox<>();
        anioCombo = new javax.swing.JComboBox<>();
        diaCombo = new javax.swing.JComboBox<>();
        diaLabel = new javax.swing.JLabel();
        mesLabel = new javax.swing.JLabel();
        adjuntarButtom = new javax.swing.JButton();
        contraText = new javax.swing.JPasswordField();
        errorImagen = new javax.swing.JLabel();
        modificateTable = new javax.swing.JButton();
        deleteTable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMongo = new javax.swing.JTable();
        confirmarEdicion = new javax.swing.JButton();
        fondoCampos = new javax.swing.JLabel();
        checkModificacion = new javax.swing.JLabel();
        MenuBaseDatos = new javax.swing.JMenuBar();
        exitMenu = new javax.swing.JMenu();
        backMenu = new javax.swing.JMenuItem();
        exitMenuAdd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombresLabel.setText("Nombres Completos");
        jPanel2.add(NombresLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 164, -1));

        anioLabel.setText("Año");
        jPanel2.add(anioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 100, -1));

        emailLabel.setText("Email");
        jPanel2.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 183, -1));

        errorNames.setForeground(new java.awt.Color(255, 0, 51));
        errorNames.setText("Error, tiene que tener un nombre y un apellido");
        jPanel2.add(errorNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 30));

        telfLabel.setText("Telefono");
        jPanel2.add(telfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 183, -1));

        errorContra.setForeground(new java.awt.Color(255, 0, 51));
        errorContra.setText("Contraseña incorrecta");
        jPanel2.add(errorContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 183, -1));

        errorPhone.setForeground(new java.awt.Color(255, 0, 51));
        errorPhone.setText("Telefono incorrecto");
        jPanel2.add(errorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 183, -1));

        errorCedula.setForeground(new java.awt.Color(255, 0, 51));
        errorCedula.setText("Cedula Incorrecta");
        jPanel2.add(errorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 183, -1));

        namesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namesTextActionPerformed(evt);
            }
        });
        jPanel2.add(namesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 189, -1));

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        jPanel2.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 183, -1));

        phoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextActionPerformed(evt);
            }
        });
        jPanel2.add(phoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 183, -1));

        saveTable.setText("GUARDAR");
        saveTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTableActionPerformed(evt);
            }
        });
        jPanel2.add(saveTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        mesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesComboActionPerformed(evt);
            }
        });
        jPanel2.add(mesCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, 30));

        genderLabel.setText("Genero");
        jPanel2.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 183, -1));

        languajeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "English" }));
        languajeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languajeComboActionPerformed(evt);
            }
        });
        jPanel2.add(languajeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, -1, -1));

        cedulaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaTextActionPerformed(evt);
            }
        });
        jPanel2.add(cedulaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 183, -1));

        cedulaLabel.setText("Cedula");
        jPanel2.add(cedulaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        contraLabel.setText("Contraseña");
        jPanel2.add(contraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, -1));

        errorEmail.setForeground(new java.awt.Color(255, 0, 51));
        errorEmail.setText("Email incorrecto");
        jPanel2.add(errorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 183, -1));

        generoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "No Binario", "Otro" }));
        generoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoComboActionPerformed(evt);
            }
        });
        jPanel2.add(generoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 90, 30));

        anioCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        anioCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioComboActionPerformed(evt);
            }
        });
        jPanel2.add(anioCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 90, 30));

        diaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaComboActionPerformed(evt);
            }
        });
        jPanel2.add(diaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 90, 30));

        diaLabel.setText("Dia");
        jPanel2.add(diaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 100, -1));

        mesLabel.setText("Mes");
        jPanel2.add(mesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 100, -1));

        adjuntarButtom.setText("Adjuntar Imagen de Perfil");
        adjuntarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjuntarButtomActionPerformed(evt);
            }
        });
        jPanel2.add(adjuntarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));
        jPanel2.add(contraText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, -1));

        errorImagen.setText("<html>\n<p>\n  Seleccione una imagen con las siguientes características:<br>\n  Formato: JPG, JPEG, PNG<br>\n  Tamaño: 413 x 531 píxeles\n</p>\n</html>");
        jPanel2.add(errorImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 230, 60));

        modificateTable.setText("MODIFICAR");
        modificateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificateTableActionPerformed(evt);
            }
        });
        jPanel2.add(modificateTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        deleteTable.setText("ELIMINAR");
        deleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTableActionPerformed(evt);
            }
        });
        jPanel2.add(deleteTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        tablaMongo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMongo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 940, 230));

        confirmarEdicion.setText("Confirmar Edicion");
        jPanel2.add(confirmarEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        fondoCampos.setBackground(new java.awt.Color(255, 255, 255));
        fondoCampos.setOpaque(true);
        jPanel2.add(fondoCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 680, 220));
        jPanel2.add(checkModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1060, 590));

        jPanel1.add(jPanel2, "card2");

        MenuBaseDatos.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        exitMenu.setText("Exit");

        backMenu.setText("Regresar");
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });
        exitMenu.add(backMenu);

        exitMenuAdd.setText("Salir");
        exitMenuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuAddActionPerformed(evt);
            }
        });
        exitMenu.add(exitMenuAdd);

        MenuBaseDatos.add(exitMenu);

        setJMenuBar(MenuBaseDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTableActionPerformed

    }//GEN-LAST:event_saveTableActionPerformed

    private void namesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namesTextActionPerformed
        
    }//GEN-LAST:event_namesTextActionPerformed

    private void phoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void exitMenuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuAddActionPerformed

    }//GEN-LAST:event_exitMenuAddActionPerformed

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed

    }//GEN-LAST:event_backMenuActionPerformed

    private void languajeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languajeComboActionPerformed

    }//GEN-LAST:event_languajeComboActionPerformed

    private void mesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesComboActionPerformed

    private void cedulaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaTextActionPerformed

    private void generoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoComboActionPerformed

    private void anioComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioComboActionPerformed

    private void diaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaComboActionPerformed

    private void adjuntarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjuntarButtomActionPerformed

    }//GEN-LAST:event_adjuntarButtomActionPerformed

    private void modificateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificateTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificateTableActionPerformed

    private void deleteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTableActionPerformed
       
    }//GEN-LAST:event_deleteTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaClienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaClienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaClienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaClienteNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaClienteNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBaseDatos;
    public javax.swing.JLabel NombresLabel;
    public javax.swing.JButton adjuntarButtom;
    public javax.swing.JComboBox<String> anioCombo;
    public javax.swing.JLabel anioLabel;
    public javax.swing.JMenuItem backMenu;
    public javax.swing.JLabel cedulaLabel;
    public javax.swing.JTextField cedulaText;
    public javax.swing.JLabel checkModificacion;
    public javax.swing.JButton confirmarEdicion;
    public javax.swing.JLabel contraLabel;
    public javax.swing.JPasswordField contraText;
    public javax.swing.JButton deleteTable;
    public javax.swing.JComboBox<String> diaCombo;
    public javax.swing.JLabel diaLabel;
    public javax.swing.JLabel emailLabel;
    public javax.swing.JTextField emailText;
    public javax.swing.JLabel errorCedula;
    public javax.swing.JLabel errorContra;
    public javax.swing.JLabel errorEmail;
    public javax.swing.JLabel errorImagen;
    public javax.swing.JLabel errorNames;
    public javax.swing.JLabel errorPhone;
    public javax.swing.JMenu exitMenu;
    public javax.swing.JMenuItem exitMenuAdd;
    private javax.swing.JLabel fondoCampos;
    public javax.swing.JLabel genderLabel;
    public javax.swing.JComboBox<String> generoCombo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> languajeCombo;
    public javax.swing.JComboBox<String> mesCombo;
    public javax.swing.JLabel mesLabel;
    public javax.swing.JButton modificateTable;
    public javax.swing.JTextField namesText;
    public javax.swing.JTextField phoneText;
    public javax.swing.JButton saveTable;
    public static javax.swing.JTable tablaMongo;
    public javax.swing.JLabel telfLabel;
    // End of variables declaration//GEN-END:variables
}
