/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface.ViewCliente;

import Interface.Controlador.ControladorPanelCliente;


/**
 *
 * @author Rayson
 */
public class PanelCliente extends javax.swing.JPanel {
    private ControladorPanelCliente control;
    /**
     * Creates new form NewJPanel
     */
    public PanelCliente() {
        this.control=new ControladorPanelCliente(this);
    }
    public void IniciarComponentes(){
        initComponents();   
        this.setSize(1200,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelClientePrincipal = new javax.swing.JPanel();
        ayudaPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        derechos = new javax.swing.JLabel();
        Cabecera = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        ComprarButtom = new javax.swing.JButton();
        PublicarButtom = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        showPButtom = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 630));
        setLayout(new java.awt.CardLayout());

        PanelClientePrincipal.setPreferredSize(new java.awt.Dimension(1260, 600));
        PanelClientePrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ayudaPanel.setBackground(new java.awt.Color(204, 204, 255));
        ayudaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Ayuda");
        ayudaPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 40));

        derechos.setText("@");
        ayudaPanel.add(derechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 170, 90));

        PanelClientePrincipal.add(ayudaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 120, 874));

        Cabecera.setBackground(new java.awt.Color(0, 102, 204));
        Cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/Logo.jpeg"))); // NOI18N
        logo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cabecera.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Version 1.0");
        Cabecera.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        PanelClientePrincipal.add(Cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1270, 80));

        panelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setText("Comprar Propiedades");
        panelCliente.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 150, 120));

        jTextField3.setEditable(false);
        jTextField3.setText("Publicar Propiedad");
        panelCliente.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 170, 120));

        ComprarButtom.setText("Entrar");
        panelCliente.add(ComprarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 150, 50));

        PublicarButtom.setText("Entrar");
        panelCliente.add(PublicarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 170, 50));

        jLabel2.setText("MENU DEL CLIENTE");
        panelCliente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setText("MOSTRAR PROPIEDADES PUBLICADAS");
        panelCliente.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 120));

        showPButtom.setText("Entrar");
        panelCliente.add(showPButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, 50));

        PanelClientePrincipal.add(panelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 570, 370));

        add(PanelClientePrincipal, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Cabecera;
    public javax.swing.JButton ComprarButtom;
    public javax.swing.JPanel PanelClientePrincipal;
    public javax.swing.JButton PublicarButtom;
    public javax.swing.JPanel ayudaPanel;
    private javax.swing.JLabel derechos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel logo;
    public javax.swing.JPanel panelCliente;
    public javax.swing.JButton showPButtom;
    // End of variables declaration//GEN-END:variables
}
