package Interface;


import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rayson
 */
public class Login extends javax.swing.JFrame {
        /**
     * Creates new form Inferdaz
     */
    public Login() {
        initComponents();
        errorId.setVisible(false);
        errorPassword.setVisible(false);
        
        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/BackgroundImages/FondoLogin.gif"));
        Icon fondo1=new ImageIcon(imagenFondo.getImage().getScaledInstance(FONDO.getWidth(), FONDO.getHeight(),Image.SCALE_DEFAULT));
        FONDO.setIcon(fondo1);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        login = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        errorId = new javax.swing.JLabel();
        errorPassword = new javax.swing.JLabel();
        passwordL = new javax.swing.JLabel();
        usuarioL = new javax.swing.JLabel();
        ButtomIniciar = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        fondoL = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 180, -1));

        login.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        login.setText("INICIO DE SESION");
        login.setToolTipText("");
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 400, 30));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 180, -1));

        errorId.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        errorId.setForeground(new java.awt.Color(255, 51, 102));
        errorId.setText("ID Invalido");
        getContentPane().add(errorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, 30));

        errorPassword.setBackground(new java.awt.Color(255, 51, 51));
        errorPassword.setFont(new java.awt.Font("Segoe UI Emoji", 2, 12)); // NOI18N
        errorPassword.setForeground(new java.awt.Color(255, 51, 51));
        errorPassword.setText("Password Incorrecta");
        getContentPane().add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 130, 20));

        passwordL.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        passwordL.setText("PASSWORD");
        getContentPane().add(passwordL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        usuarioL.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        usuarioL.setText("USUARIO");
        getContentPane().add(usuarioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        ButtomIniciar.setBackground(new java.awt.Color(204, 203, 255));
        ButtomIniciar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        ButtomIniciar.setText("Iniciar");
        ButtomIniciar.setToolTipText("");
        ButtomIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtomIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 130, 40));

        exit.setBackground(new java.awt.Color(205, 204, 255));
        exit.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 110, 40));

        fondoL.setBackground(new java.awt.Color(202, 179, 224));
        fondoL.setOpaque(true);
        getContentPane().add(fondoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 220, 190));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/FondoLogin.gif"))); // NOI18N
        FONDO.setDoubleBuffered(true);
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 650, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed

    }//GEN-LAST:event_idActionPerformed

    private void ButtomIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomIniciarActionPerformed
    // Obtener los valores ingresados
    String enteredId = id.getText().trim();
    char[] passwordArray = password.getPassword();
    String enteredPassword = new String(passwordArray).trim();

    // Validar el campo ID
    if (enteredId.isEmpty()) {
        errorId.setText("El ID no puede estar vacío");
        errorId.setVisible(true);
        return; // Salir del método si el ID está vacío
    } else if (!enteredId.matches("\\d{10}")) {
        errorId.setText("ID debe contener exactamente 10 dígitos numéricos");
        errorId.setVisible(true);
        return; // Salir del método si el ID no cumple con el formato
    } else {
        errorId.setVisible(false);
    }

    // Validar el campo contraseña
    if (passwordArray.length == 0) {
        errorPassword.setText("La contraseña no puede estar vacía");
        errorPassword.setVisible(true);
    } else {
        errorPassword.setVisible(false);
    }

    // Verificar las credenciales ingresadas
    if (!enteredId.isEmpty() && enteredId.matches("\\d{10}") && !enteredPassword.isEmpty()) {
        if (enteredId.equals("1234567890") && enteredPassword.equals("password")) {
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.", "Login", JOptionPane.INFORMATION_MESSAGE);
            abrirMenuPrincipal();
            id.setText("");
            password.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "ID o contraseña incorrecta", "Login", JOptionPane.ERROR_MESSAGE);
            password.setText("");
        }
    }
    }//GEN-LAST:event_ButtomIniciarActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       this.dispose();
    }//GEN-LAST:event_exitActionPerformed
    private void abrirMenuPrincipal() {
        // Crear una instancia de menuPrincipal y hacerla visible
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        // Ocultar la ventana de login actual
        this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* Ifor details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtomIniciar;
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel errorId;
    private javax.swing.JLabel errorPassword;
    private javax.swing.JButton exit;
    private javax.swing.JLabel fondoL;
    private javax.swing.JTextField id;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordL;
    private javax.swing.JLabel usuarioL;
    // End of variables declaration//GEN-END:variables
}
