/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfaceMenuPrincipalView;

import Interface.ViewAdmin.VISTAPanelADMIN;
import Interface.Controlador.ControladorMenuPrincipal;
import Login.Vista.Login;

/**
 *
 * @author Rayson
 */
public class MenuPrincipalAdmin extends javax.swing.JFrame {
    /**
     * Creates new form MenuPrincipalAdmin
     */
    public MenuPrincipalAdmin() {
        initComponents();
        this.setSize(800,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCambio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuBaseDatos = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        INICIO = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        buscarA = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenu();
        exitMenuAdd = new javax.swing.JMenuItem();
        backMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCambio.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Menu Admin");
        PanelCambio.add(jLabel1, "card2");

        MenuBaseDatos.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jMenu5.setText("Administrador");

        INICIO.setText("INICIO");
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });
        jMenu5.add(INICIO);

        MenuBaseDatos.add(jMenu5);

        jMenu7.setText("Buscar");

        buscarA.setText("Buscar");
        buscarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAActionPerformed(evt);
            }
        });
        jMenu7.add(buscarA);

        MenuBaseDatos.add(jMenu7);

        exitMenu.setText("Exit");

        exitMenuAdd.setText("Salir");
        exitMenuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuAddActionPerformed(evt);
            }
        });
        exitMenu.add(exitMenuAdd);

        backMenu.setText("Regresar");
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });
        exitMenu.add(backMenu);

        MenuBaseDatos.add(exitMenu);

        setJMenuBar(MenuBaseDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAActionPerformed

    }//GEN-LAST:event_buscarAActionPerformed

    private void exitMenuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuAddActionPerformed
        ControladorMenuPrincipal control=new ControladorMenuPrincipal();
        control.MensajeConfirmacion(this);
    }//GEN-LAST:event_exitMenuAddActionPerformed

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed
        // Ocultar la ventana actual
        this.setVisible(false);
        // Crear y mostrar la ventana de login
        new Login().setVisible(true);
    }//GEN-LAST:event_backMenuActionPerformed

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
       ControladorMenuPrincipal control=new ControladorMenuPrincipal();
       VISTAPanelADMIN panelAdmin=new VISTAPanelADMIN();
       control.nuevoPanel(PanelCambio, panelAdmin, "Panel Del Cliente");
    }//GEN-LAST:event_INICIOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem INICIO;
    private javax.swing.JMenuBar MenuBaseDatos;
    private javax.swing.JPanel PanelCambio;
    private javax.swing.JMenuItem backMenu;
    private javax.swing.JMenuItem buscarA;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuItem exitMenuAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    // End of variables declaration//GEN-END:variables
}
