package InterfaceMenuPrincipalView;

import Interface.ViewCliente.BuscarPropiedades;
import Interface.ViewCliente.PanelCliente;
import Interface.Controlador.ControladorMenuPrincipal;
import Login.Vista.Login;
import java.awt.CardLayout;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Rayson
 */
public class MenuPrincipalCliente extends javax.swing.JFrame {
    /**
     * Creates new form MenuPrincipalCliente
     */
    public MenuPrincipalCliente() {
        initComponents();
        setTitle("P2Lab2LopezRayson");
        setSize(800,600);
        // Configurar la operación de cierre para salir de la aplicación
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        PanelCambio.add(jLabel1,"card2");
        CardLayout layout=(CardLayout)PanelCambio.getLayout();
        layout.show(PanelCambio,"card2");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCambio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuBaseDatos = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Buscar = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenu();
        exitMenuAdd = new javax.swing.JMenuItem();
        backMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCambio.setLayout(new java.awt.CardLayout());

        jLabel1.setText("MENU PRINCIPAL");
        PanelCambio.add(jLabel1, "card2");

        MenuBaseDatos.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jMenu4.setText("Cliente");

        Cliente.setText("INICIO");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        jMenu4.add(Cliente);

        MenuBaseDatos.add(jMenu4);

        jMenu3.setText("Buscar");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jMenu3.add(Buscar);

        MenuBaseDatos.add(jMenu3);

        exitMenu.setText("Exit");

        exitMenuAdd.setText("Salir");
        exitMenuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuAddActionPerformed(evt);
            }
        });
        exitMenu.add(exitMenuAdd);

        backMenu.setText("Regresar");
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });
        exitMenu.add(backMenu);

        MenuBaseDatos.add(exitMenu);

        setJMenuBar(MenuBaseDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        ControladorMenuPrincipal control=new ControladorMenuPrincipal();
        BuscarPropiedades buscarP=new BuscarPropiedades();
        control.nuevoPanel(PanelCambio, buscarP, "Panel de Buscar");
    }//GEN-LAST:event_BuscarActionPerformed

    private void exitMenuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuAddActionPerformed
        int confirm = JOptionPane.showOptionDialog(
            this,
            "¿Estás seguro de que quieres salir?",
            "Confirmación de salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[]{"Sí", "No"},
            "No"
        );

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuAddActionPerformed

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed
        // Ocultar la ventana actual
        this.setVisible(false);
        // Crear y mostrar la ventana de login
        new Login().setVisible(true);
    }//GEN-LAST:event_backMenuActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
       ControladorMenuPrincipal control=new ControladorMenuPrincipal();
       PanelCliente panelCliente=new PanelCliente();
       control.nuevoPanel(PanelCambio, panelCliente, "Panel Del Cliente");
    }//GEN-LAST:event_ClienteActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenuBar MenuBaseDatos;
    public javax.swing.JPanel PanelCambio;
    private javax.swing.JMenuItem backMenu;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuItem exitMenuAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    // End of variables declaration//GEN-END:variables
}
