/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface.ViewAdmin;

import Interface.Controlador.ControladorMenuPrincipal;

/**
 *
 * @author Rayson
 */
public class VISTAPanelADMIN extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdmin
     */
    public VISTAPanelADMIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCambioA = new javax.swing.JPanel();
        PanelAdmin = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        derechos1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ayuda1 = new javax.swing.JPanel();
        AdminPanel1 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        entrarVerificar = new javax.swing.JButton();
        buscarUsuarios = new javax.swing.JButton();
        Crearusuarios = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        PanelCambioA.setLayout(new java.awt.CardLayout());

        PanelAdmin.setLayout(new java.awt.CardLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setText("Ayuda");
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, 70));

        derechos1.setText("@");
        jPanel7.add(derechos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 170, 100));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 470));

        jPanel8.setBackground(new java.awt.Color(0, 102, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/Logo.jpeg"))); // NOI18N
        jPanel8.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Version 1.0");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 80));

        Ayuda1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField10.setText("Buscar Usuarios");
        AdminPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 150, 120));

        jTextField11.setText("Crear Nuevos Administradores");
        AdminPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 170, 120));

        entrarVerificar.setText("Entrar");
        entrarVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarVerificarActionPerformed(evt);
            }
        });
        AdminPanel1.add(entrarVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 50));

        buscarUsuarios.setText("Entrar");
        buscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuariosActionPerformed(evt);
            }
        });
        AdminPanel1.add(buscarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, 50));

        Crearusuarios.setText("Entrar");
        Crearusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearusuariosActionPerformed(evt);
            }
        });
        AdminPanel1.add(Crearusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 170, 50));

        jTextField12.setText("Verificar Publicaciones");
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        AdminPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 120));

        Ayuda1.add(AdminPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 550, 360));

        jLabel1.setText("MENU DEL ADMINISTRADOR");
        Ayuda1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jPanel6.add(Ayuda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 560, 420));

        PanelAdmin.add(jPanel6, "card2");

        PanelCambioA.add(PanelAdmin, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelCambioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelCambioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entrarVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarVerificarActionPerformed
        VISTAVerificarPropiedadesADMIN panelVerificar=new VISTAVerificarPropiedadesADMIN();
        ControladorMenuPrincipal menu=new ControladorMenuPrincipal();
        menu.nuevoPanel(PanelAdmin, panelVerificar, "Panel de Verificar Publicaciones");
    }//GEN-LAST:event_entrarVerificarActionPerformed

    private void buscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuariosActionPerformed
        VISTABuscarClientesADMIN panelClientes=new VISTABuscarClientesADMIN();
        ControladorMenuPrincipal control=new ControladorMenuPrincipal();
        control.nuevoPanel(PanelAdmin,panelClientes , "Menu de Buscar Clientes");
    }//GEN-LAST:event_buscarUsuariosActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void CrearusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearusuariosActionPerformed
        VISTAIngresoADMIN v1=new VISTAIngresoADMIN();
        ControladorMenuPrincipal control=new ControladorMenuPrincipal();
        control.nuevoPanel(PanelAdmin,v1,"Panel Del Cliente");
    }//GEN-LAST:event_CrearusuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel1;
    private javax.swing.JPanel Ayuda1;
    private javax.swing.JButton Crearusuarios;
    private javax.swing.JPanel PanelAdmin;
    private javax.swing.JPanel PanelCambioA;
    private javax.swing.JButton buscarUsuarios;
    private javax.swing.JLabel derechos1;
    private javax.swing.JButton entrarVerificar;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JLabel logo1;
    // End of variables declaration//GEN-END:variables
}
