/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface.ViewCliente;

import ConexionBD.ConexionBDPropiedades;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rayson
 */
public class BuscarPropiedades extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    /**
     * Creates new form BuscarP
     */
    public BuscarPropiedades() {
        initComponents();
        tableModel=new DefaultTableModel(new Object[][]{},new String[]{"Nombres Completos","Descripcion","Precio","Metros Cuadrados","Dirrecion","Disponibilidad","Numero de Cuartos","Ubicacion"})
        {
        @Override
        public boolean isCellEditable(int row,int column){
            return false;
        }
    };
        ConexionBDPropiedades conexionBD=new ConexionBDPropiedades();
        conexionBD.actualizarTablaMongo(tableModel);
        TablaMongo.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMongo = new javax.swing.JTable();
        Venta = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();

        BuscarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaMongo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaMongo);

        BuscarP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Venta.setText("Venta");
        BuscarP.add(Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 98, -1));

        jRadioButton2.setText("Arriendo");
        BuscarP.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 98, -1));

        jRadioButton3.setText("Fecha");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        BuscarP.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 98, -1));
        BuscarP.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BuscarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuscarP;
    private javax.swing.JTable TablaMongo;
    private javax.swing.JRadioButton Venta;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
