/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface.ViewCliente;

import Interface.Controlador.ControladorCliente;

/**
 *
 * @author Rayson
 */
public class PanelCliente extends javax.swing.JPanel {
    ControladorCliente control=new ControladorCliente();
    /**
     * Creates new form NewJPanel
     */
    public PanelCliente() {
        initComponents();
        control=new ControladorCliente(null,null,this);   
        PublicarButtom.addActionListener(control);
        ComprarButtom.addActionListener(control);
        entrarButtom.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelClientePrincipal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        derechos = new javax.swing.JLabel();
        Cabecera = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelCliente = new javax.swing.JPanel();
        ClientePanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        ComprarButtom = new javax.swing.JButton();
        PublicarButtom = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        entrarButtom = new javax.swing.JButton();

        PanelClientePrincipal.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Ayuda");
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 40));

        derechos.setText("@");
        jPanel4.add(derechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 170, 90));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 450));

        Cabecera.setBackground(new java.awt.Color(0, 102, 204));
        Cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/Logo.jpeg"))); // NOI18N
        Cabecera.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Version 1.0");
        Cabecera.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jPanel3.add(Cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 80));

        PanelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClientePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setText("Comprar Propiedades");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        ClientePanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 150, 120));

        jTextField3.setEditable(false);
        jTextField3.setText("Publicar Propiedad");
        ClientePanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 170, 120));

        ComprarButtom.setText("Entrar");
        ComprarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarButtomActionPerformed(evt);
            }
        });
        ClientePanel.add(ComprarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 150, 50));

        PublicarButtom.setText("Entrar");
        PublicarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicarButtomActionPerformed(evt);
            }
        });
        ClientePanel.add(PublicarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 170, 50));

        jTextField1.setEditable(false);
        jTextField1.setText("MOSTRAR PROPIEDADES PUBLICADAS");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        ClientePanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 120));

        jLabel2.setText("MENU DEL CLIENTE");
        ClientePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        entrarButtom.setText("Entrar");
        entrarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtomActionPerformed(evt);
            }
        });
        ClientePanel.add(entrarButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 50));

        PanelCliente.add(ClientePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 450));

        jPanel3.add(PanelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 610, 420));

        PanelClientePrincipal.add(jPanel3, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelClientePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(PanelClientePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void PublicarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicarButtomActionPerformed

    }//GEN-LAST:event_PublicarButtomActionPerformed

    private void ComprarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComprarButtomActionPerformed

    private void entrarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtomActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_entrarButtomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabecera;
    public javax.swing.JPanel ClientePanel;
    public javax.swing.JButton ComprarButtom;
    private javax.swing.JPanel PanelCliente;
    public javax.swing.JPanel PanelClientePrincipal;
    public javax.swing.JButton PublicarButtom;
    private javax.swing.JLabel derechos;
    public javax.swing.JButton entrarButtom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
